language: go
sudo: false
go:
- "1.12"
env:
  - GO111MODULE=on
go_import_path: github.com/tcd/md2pdf
before_install:
  - go get github.com/mattn/goveralls
script:
  - $GOPATH/bin/goveralls -service=travis-ci
  - env GO111MODULE=on go build
  - env GO111MODULE=on go test -v ./...
