package parse

import (
	"strings"

	"github.com/jung-kurt/gofpdf"
	"github.com/tcd/md2pdf/internal/render"
	"golang.org/x/net/html"
)

// HTML renders a PDF from an html string generated by blackfriday
func HTML(inputHTML, outputPath string) error {

	doc := strings.NewReader(inputHTML)
	tokenizer := html.NewTokenizer(doc)
	pdf := gofpdf.New("P", "mm", "Letter", "")
	render.Setup(pdf)

	for {
		tt := tokenizer.Next()

		if tt == html.ErrorToken {
			break // End of document
		}

		if tt == html.SelfClosingTagToken {
			T1 := tokenizer.Token()

			if T1.Data == "hr" {
				render.HR(pdf)
			}
			if T1.Data == "br" {
				// decide how to deal with these?
			}
			if T1.Data == "img" {
				Image(pdf, T1)
			}
		}

		if tt == html.StartTagToken {
			T1 := tokenizer.Token()

			if T1.Data == "h1" ||
				T1.Data == "h2" ||
				T1.Data == "h3" ||
				T1.Data == "h4" ||
				T1.Data == "h5" ||
				T1.Data == "h6" {
				Header(pdf, tokenizer, T1)
			}
			if T1.Data == "pre" {
				Codeblock(pdf, tokenizer)
			}
			if T1.Data == "p" {
				Paragraph(pdf, tokenizer, false)
			}
			if T1.Data == "blockquote" {
				Paragraph(pdf, tokenizer, true)
			}
			if T1.Data == "ol" || T1.Data == "ul" {
				List(pdf, tokenizer)
			}
			if T1.Data == "table" {
				Table(pdf, tokenizer)
			}
		}
	}

	return pdf.OutputFileAndClose(outputPath)
}
